services:
  - type: web_service
    name: parking-lot
    env: node
    plan: free
    region: oregon
    branch: main
    root: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DB_HOST
      - key: DB_USER
      - key: DB_PASSWORD
      - key: DB_NAME
      - key: DB_PORT
